version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: ci
    labels: ['skip changelog']

  # Build system
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
